-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExpiry/maintenance/db/sql/bs_expiry.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_expiry (
  exp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  exp_page_id INTEGER NOT NULL, exp_date DATETIME NOT NULL,
  exp_comment BLOB NOT NULL
);

CREATE INDEX exp_page_id_idx ON /*_*/bs_expiry (exp_page_id);

CREATE INDEX exp_date_idx ON /*_*/bs_expiry (exp_date);
