-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceExpiry/maintenance/db/bs_expiry_column_type_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE bs_expiry
  ALTER exp_date TYPE TIMESTAMPTZ;
