-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExpiry/maintenance/db/bs_expiry.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_expiry (
  exp_id SERIAL NOT NULL,
  exp_page_id INT NOT NULL,
  exp_date TIMESTAMPTZ NOT NULL,
  exp_comment TEXT NOT NULL,
  PRIMARY KEY(exp_id)
);

CREATE INDEX exp_page_id_idx ON bs_expiry (exp_page_id);

CREATE INDEX exp_date_idx ON bs_expiry (exp_date);
