-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceExpiry/maintenance/db/bs_expiry_column_type_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__bs_expiry AS
SELECT
  exp_id,
  exp_page_id,
  exp_date,
  exp_comment
FROM /*_*/bs_expiry;
DROP TABLE /*_*/bs_expiry;


CREATE TABLE /*_*/bs_expiry (
    exp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    exp_page_id INTEGER NOT NULL, exp_date DATETIME NOT NULL,
    exp_comment BLOB NOT NULL
  );
INSERT INTO /*_*/bs_expiry (
    exp_id, exp_page_id, exp_date, exp_comment
  )
SELECT
  exp_id,
  exp_page_id,
  exp_date,
  exp_comment
FROM
  /*_*/__temp__bs_expiry;
DROP TABLE /*_*/__temp__bs_expiry;

CREATE INDEX exp_page_id_idx ON /*_*/bs_expiry (exp_page_id);

CREATE INDEX exp_date_idx ON /*_*/bs_expiry (exp_date);
